### PR TITLE
Update cookbook dependencies

### PR DESCRIPTION
**Pull request by fgs-dbudwin**
Nothing fancy, just searched the Chef supermarket for the latest versions of our dependencies.

### CODE REVIEW

**Comment by fgs-dbudwin** [comment]
It looks like this cookbook Jenkins build has never passed and failing continuously for the same reasons.

**Comment by FGS-BMarkham** [comment]
That sounds vaguely familiar to me. I think I had gotten @FGS-PKnouff to volunteer to take a look at this (and some other cookbook problems I was having) at one point, but that was a while ago and I don't think we got around to this one. I think I decided that I didn't absolutely need to install Terraform on our Linux node just yet, which is why this problem has lingered.

**Comment by fgs-dbudwin** [comment]
@FGS-PKnouff @FGS-BMarkham what should we do with this PR then?  This is the last piece for me to complete our ISMS updates of cookbooks.

**Comment by FGS-BMarkham** [comment]
I recommend leaving the PR open but for the ISMS card call the effort "done". If we don't get back to this by some point that we would have called it "dead", then we can close it when we revisit it.

**Comment by fgs-dbudwin** [comment]
This repo had [a tech debt card filed for it](https://foxguardsolutions.visualstudio.com/CyberSecurity/_workitems/edit/3691) to mark this repo as archived.

**Pull request closed without merging**
